from economy import Economy
economy = Economy(id = "FIRS",
                  numeric_id = 2,
                  # as of May 2015 the following cargos must have fixed positions if used by an economy:
                  # passengers: 0, mail: 2, goods 5, food 11
                  # keep the rest of the cargos alphabetised
                  # bump the min. compatible version if this list changes
                  cargos = ['passengers',
							'acid',
                            'mail',
                            'alcohol',
                            'bauxite',
							'goods',
							'beans',
                            'building_materials',
							'cement',
                            'chemicals',
							'chlorine',
                            'food',
                            'clay',
                            'coal',
							'coke',
							'copper',
                            'copper_ore',
                            'edible_oil',
							'electrical_machines',
                            'engineering_supplies',
                            'explosives',
                            'farm_supplies',
                            'fertiliser',
                            'fish',
                            'fruits',
                            'grain',
                            'iron_ore',
                            'kaolin',
							'limestone',
                            'livestock',
                            'lumber',
							'manganese',
                            'metal',
                            'milk',
							'nitrates',
                            'oil',
							'packaging',
                            'paper',
                            'peat',
                            'petrol',
                            'phosphate',
							'pig_iron',
                            'pipe',
                            'plant_fibres',
							'pyrite_ore',
							'quicklime',
                            'recyclables',
                            'rubber',
							'salt',
                            'sand',
                            'scrap_metal',
							'slag',
                            'soda_ash',
                            'steel',
                            'sugar_beet',
                            'sulphur',
							'vehicle_bodies',
							'vehicle_parts',
                            'vehicles',
                            'wood',
                            'wool',
							'zinc'])
